export const provinces = [
  { name: '서울' },
  { name: '부산' },
  { name: '강원' },
  { name: '충남' },
  { name: '경기' },
  { name: '인천' },
  { name: '충북' },
  { name: '전북' },
  { name: '광주' },
  { name: '울산' },
  { name: '전남' },
  { name: '경남' },
  { name: '대전' },
  { name: '세종' },
  { name: '경북' },
  { name: '제주' },
];

export const provinceCity = {
  서울: {
    종로구: { count: 0 },
    중구: { count: 0 },
    용산구: { count: 0 },
    성동구: { count: 0 },
    광진구: { count: 0 },
    동대문구: { count: 0 },
    중랑구: { count: 0 },
    성북구: { count: 0 },
    강북구: { count: 0 },
    도봉구: { count: 0 },
    노원구: { count: 0 },
    은평구: { count: 0 },
    서대문구: { count: 0 },
    마포구: { count: 0 },
    양천구: { count: 0 },
    강서구: { count: 0 },
    구로구: { count: 0 },
    금천구: { count: 0 },
    영등포구: { count: 0 },
    동작구: { count: 0 },
    관악구: { count: 0 },
    서초구: { count: 0 },
    강남구: { count: 0 },
    송파구: { count: 0 },
    강동구: { count: 0 },
  },
  부산: {
    서구: { count: 0 },
    동구: { count: 0 },
    영도구: { count: 0 },
    부산진구: { count: 0 },
    동래구: { count: 0 },
    남구: { count: 0 },
    북구: { count: 0 },
    해운대구: { count: 0 },
    사하구: { count: 0 },
    금정구: { count: 0 },
    연제구: { count: 0 },
    수영구: { count: 0 },
    사상구: { count: 0 },
    기장군: { count: 0 },
  },
  대구: {
    수성구: { count: 0 },
    달서구: { count: 0 },
    달성군: { count: 0 },
  },
  인천: {
    중구영종출장: { count: 0 },
    중구용유출장: { count: 0 },
    미추홀구: { count: 0 },
    연수구: { count: 0 },
    남동구: { count: 0 },
    부평구: { count: 0 },
    계양구: { count: 0 },
    서구검단출장: { count: 0 },
    강화군: { count: 0 },
    옹진군: { count: 0 },
  },
  광주: {
    광산구: { count: 0 },
  },
  대전: {
    유성구: { count: 0 },
    대덕구: { count: 0 },
  },
  울산: {
    울주군: { count: 0 },
  },
  경기도: {
    '수원시 장안구': { count: 0 },
    '수원시 권선구': { count: 0 },
    '수원시 팔달구': { count: 0 },
    '수원시 영통구': { count: 0 },
    '성남시 수정구': { count: 0 },
    '성남시 중원구': { count: 0 },
    '성남시 분당구': { count: 0 },
    의정부시: { count: 0 },
    '안양시 만안구': { count: 0 },
    '안양시 동안구': { count: 0 },
    부천시: { count: 0 },
    광명시: { count: 0 },
    평택시: { count: 0 },
    동두천시: { count: 0 },
    '안산시 상록구': { count: 0 },
    '안산시 단원구': { count: 0 },
    '고양시 덕양구': { count: 0 },
    '고양시 일산동구': { count: 0 },
    '고양시 일산서구': { count: 0 },
    과천시: { count: 0 },
    구리시: { count: 0 },
    남양주시: { count: 0 },
    오산시: { count: 0 },
    시흥시: { count: 0 },
    군포시: { count: 0 },
    의왕시: { count: 0 },
    하남시: { count: 0 },
    '용인시 처인구': { count: 0 },
    '용인시 기흥구': { count: 0 },
    '용인시 수지구': { count: 0 },
    파주시: { count: 0 },
    이천시: { count: 0 },
    안성시: { count: 0 },
    김포시: { count: 0 },
    화성시: { count: 0 },
    광주시: { count: 0 },
    양주시: { count: 0 },
    포천시: { count: 0 },
    여주시: { count: 0 },
    연천군: { count: 0 },
    가평군: { count: 0 },
    양평군: { count: 0 },
  },
  강원도: {
    춘천시: { count: 0 },
    원주시: { count: 0 },
    강릉시: { count: 0 },
    동해시: { count: 0 },
    태백시: { count: 0 },
    속초시: { count: 0 },
    삼척시: { count: 0 },
    홍천군: { count: 0 },
    횡성군: { count: 0 },
    영월군: { count: 0 },
    평창군: { count: 0 },
    정선군: { count: 0 },
    철원군: { count: 0 },
    화천군: { count: 0 },
    양구군: { count: 0 },
    인제군: { count: 0 },
    고성군: { count: 0 },
    양양군: { count: 0 },
  },
  충북: {
    '청주시 상당구': { count: 0 },
    '청주시 서원구': { count: 0 },
    '청주시 흥덕구': { count: 0 },
    '청주시 청원구': { count: 0 },
    충주시: { count: 0 },
    제천시: { count: 0 },
    보은군: { count: 0 },
    옥천군: { count: 0 },
    영동군: { count: 0 },
    증평군: { count: 0 },
    진천군: { count: 0 },
    괴산군: { count: 0 },
    음성군: { count: 0 },
    단양군: { count: 0 },
  },
  충남: {
    '천안시 동남구': { count: 0 },
    '천안시 서북구': { count: 0 },
    공주시: { count: 0 },
    보령시: { count: 0 },
    아산시: { count: 0 },
    서산시: { count: 0 },
    논산시: { count: 0 },
    계룡시: { count: 0 },
    당진시: { count: 0 },
    금산군: { count: 0 },
    부여군: { count: 0 },
    서천군: { count: 0 },
    청양군: { count: 0 },
    홍성군: { count: 0 },
    예산군: { count: 0 },
    태안군: { count: 0 },
  },
  전북: {
    '전주시 완산구': { count: 0 },
    '전주시 덕진구': { count: 0 },
    전주시효자출: { count: 0 },
    군산시: { count: 0 },
    익산시: { count: 0 },
    익산시함열출: { count: 0 },
    정읍시: { count: 0 },
    남원시: { count: 0 },
    김제시: { count: 0 },
    완주군: { count: 0 },
    진안군: { count: 0 },
    무주군: { count: 0 },
    장수군: { count: 0 },
    임실군: { count: 0 },
    순창군: { count: 0 },
    고창군: { count: 0 },
    부안군: { count: 0 },
  },
  전남: {
    목포시: { count: 0 },
    여수시: { count: 0 },
    순천시: { count: 0 },
    나주시: { count: 0 },
    광양시: { count: 0 },
    담양군: { count: 0 },
    곡성군: { count: 0 },
    구례군: { count: 0 },
    고흥군: { count: 0 },
    보성군: { count: 0 },
    화순군: { count: 0 },
    장흥군: { count: 0 },
    강진군: { count: 0 },
    해남군: { count: 0 },
    영암군: { count: 0 },
    무안군: { count: 0 },
    함평군: { count: 0 },
    영광군: { count: 0 },
    장성군: { count: 0 },
    완도군: { count: 0 },
    진도군: { count: 0 },
    신안군: { count: 0 },
  },
  경북: {
    '포항시 남구': { count: 0 },
    '포항시 북구': { count: 0 },
    경주시: { count: 0 },
    김천시: { count: 0 },
    안동시: { count: 0 },
    구미시: { count: 0 },
    영주시: { count: 0 },
    영천시: { count: 0 },
    상주시: { count: 0 },
    문경시: { count: 0 },
    경산시: { count: 0 },
    군위군: { count: 0 },
    의성군: { count: 0 },
    청송군: { count: 0 },
    영양군: { count: 0 },
    영덕군: { count: 0 },
    청도군: { count: 0 },
    고령군: { count: 0 },
    성주군: { count: 0 },
    칠곡군: { count: 0 },
    예천군: { count: 0 },
    봉화군: { count: 0 },
    울진군: { count: 0 },
    울릉군: { count: 0 },
  },
  경남: {
    '창원시 의창구': { count: 0 },
    '창원시 성산구': { count: 0 },
    '창원시 마산합포구': { count: 0 },
    '창원시 마산회원구': { count: 0 },
    '창원시 진해구': { count: 0 },
    진주시: { count: 0 },
    통영시: { count: 0 },
    사천시: { count: 0 },
    사천남양출장: { count: 0 },
    김해시: { count: 0 },
    밀양시: { count: 0 },
    거제시: { count: 0 },
    양산시: { count: 0 },
    의령군: { count: 0 },
    함안군: { count: 0 },
    창녕군: { count: 0 },
    남해군: { count: 0 },
    하동군: { count: 0 },
    산청군: { count: 0 },
    함양군: { count: 0 },
    거창군: { count: 0 },
    합천군: { count: 0 },
  },
  제주: {
    제주시: { count: 0 },
    서귀포시: { count: 0 },
  },
  세종: {
    반곡동: { count: 0 },
    소담동: { count: 0 },
    보람동: { count: 0 },
    대평동: { count: 0 },
    가람동: { count: 0 },
    한솔동: { count: 0 },
    나성동: { count: 0 },
    새롬동: { count: 0 },
    다정동: { count: 0 },
    어진동: { count: 0 },
    종촌동: { count: 0 },
    고운동: { count: 0 },
    아름동: { count: 0 },
    도담동: { count: 0 },
    조치원읍: { count: 0 },
    연기면: { count: 0 },
    연동면: { count: 0 },
    부강면: { count: 0 },
    금남면: { count: 0 },
    장군면: { count: 0 },
    연서면: { count: 0 },
    전의면: { count: 0 },
    전동면: { count: 0 },
    소정면: { count: 0 },
  },
};
